# Interactive component
<h3>Monthly newly reported COVID-19 cases</h3>

<div>In this part, we use D3 to create a world map that shows the newly reported COVID-19 cases per month in every country. The color scale indicates the number of newly reported cases per month. User can use the form or the buttons to select a specific month and show the result.</div>

<div id="plot"></div>

<div>From the plot we can clearly see how COVID-19 spread over time.At first the COVID-19 spread from China. After two months (from March 2020), the number of newly reported cases in U.S. is far more than the other countries. As time goes by, we can see that U.S., Russia, India and Brazil have the highest number of reported cases in most of the time intervals.</div>
<style>
path {
  stroke: white;
  stroke-width: 0.25px;
  fill: grey;
}
</style>

<script src="https://d3js.org/d3.v7.js"></script>
<script src="https://unpkg.com/topojson@3"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3-legend/2.25.6/d3-legend.min.js"></script>
<script>
const width = 1500;
const height = 600;

const form = d3.select('div#plot')
  .append('form')
  .attr('class', 'form-inline');
  
const select = form.append('select')
  .attr('class', 'form-control')
  .attr('id', 'my_month');
const months = ['2020/1/1', '2020/2/1', '2020/3/1', '2020/4/1','2020/5/1','2020/6/1','2020/7/1','2020/8/1','2020/9/1','2020/10/1','2020/11/1','2020/12/1',
  '2021/1/1','2021/2/1','2021/3/1','2021/4/1','2021/5/1','2021/6/1','2021/7/1','2021/8/1','2021/9/1','2021/10/1','2021/11/1','2021/12/1',
  '2022/1/1','2022/2/1','2022/3/1','2022/4/1','2022/5/1','2022/6/1','2022/7/1','2022/8/1','2022/9/1','2022/10/1','2022/11/1','2022/12/1',
];
select.selectAll('option')
  .data(months)
  .enter()
  .append('option')
    .attr('value', d => d)
    .text(d => d);

const prebtn = d3.select('div#plot').append('button').attr('id','premonth').text("Previous month")
const nxtbtn = d3.select('div#plot').append('button').attr('id','nxtmonth').text('Next month')

const covidData = d3.csv('https://raw.githubusercontent.com/amethystorm/public_data_selfuse/main/monthly_with_code.csv').then(function(data){


  let filtered_data = data.filter(d=>d.month == "2020/1/1")
  let colorScale = d3.scaleSequential(d3.interpolateReds)
  .domain([0, d3.max(filtered_data, d => Number(d.New_cases))]);


  const projection = d3.geoMercator()
      .center([0, 5 ])
      .scale(120)
      .rotate([-180,0]);

  const svg = d3.select("div#plot")
      .append("svg")
      .attr("width", width)
      .attr("height", height);

  const path = d3.geoPath()
      .projection(projection);

  const g = svg.append("g");

  let legend = d3.legendColor().scale(colorScale);
  let legend_svg = svg.append("svg")
    .attr("transform", "translate(500,10)")
  
  legend_svg.call(legend);

  // load and display the World
  d3.json("https://unpkg.com/world-atlas@1.1.4/world/110m.json").then(function(topology) {

      g.selectAll("path")
        .data(topojson.feature(topology, topology.objects.countries).features)
        .enter()
        .append("path")
        .attr("d", path)
        .style('fill',d=>{
          const countrydata = filtered_data.find(
            country => Number(country.code) == Number(d.id) 
          )
          if (typeof(countrydata) == "undefined"){
            return colorScale(0)
          }
          else{
            return colorScale(countrydata.New_cases)
          }
          //return countryData ? colorScale(countryData.New_cases) : '#ccc';
        })
        .style('stroke', '#333');

  });

  prebtn.on('click', () => {
    let curmonth = d3.select('.form-control#my_month').node().value;

    currindex = months.findIndex((e)=>e==curmonth)
    preidx = -1
    if (currindex==0){
      preidx = 35
    }
    else{
      preidx = currindex - 1
    }
    month = months[preidx]
    d3.select('.form-control#my_month').node().value = month
    // update the data to only include cases for the selected month
    filtered_data = data.filter(d=>d.month == month)
    // update the color scale
    colorScale.domain([0, d3.max(filtered_data, d => Number(d.New_cases))]);

    legend = d3.legendColor().scale(colorScale);
    legend_svg.call(legend);
    svg.selectAll('path')
    .transition()
    .duration(100)
    .style('fill', d => {
    // find the corresponding data for this country
    const countrydata = filtered_data.find(
      country => Number(country.code) == Number(d.id) 
    )
    if (typeof(countrydata) == "undefined"){
      return colorScale(0)
    }
    else{
      return colorScale(countrydata.New_cases)
    }
    })
  });

  nxtbtn.on('click', () => {
    let curmonth = d3.select('.form-control#my_month').node().value;

    currindex = months.findIndex((e)=>e==curmonth)
    preidx = -1
    if (currindex==35){
      preidx = 0
    }
    else{
      preidx = currindex + 1
    }
    month = months[preidx]
    d3.select('.form-control#my_month').node().value = month
    // update the data to only include cases for the selected month
    filtered_data = data.filter(d=>d.month == month)
      // update the color scale
    colorScale.domain([0, d3.max(filtered_data, d => Number(d.New_cases))]);

    legend = d3.legendColor().scale(colorScale);
    legend_svg.call(legend);

    svg.selectAll('path')
    .transition()
    .duration(100)
    .style('fill', d => {
    // find the corresponding data for this country
    const countrydata = filtered_data.find(
      country => Number(country.code) == Number(d.id) 
    )
    if (typeof(countrydata) == "undefined"){
      return colorScale(0)
    }
    else{
      return colorScale(countrydata.New_cases)
    }
    })
  });

  select.on('change', () => {
  // get the selected month
  const month = d3.select('.form-control#my_month').node().value;

  // update the data to only include cases for the selected month
  filtered_data = data.filter(d=>d.month == month)

  // update the color scale
  colorScale.domain([0, d3.max(filtered_data, d => Number(d.New_cases))]);

    legend = d3.legendColor().scale(colorScale);
    legend_svg.call(legend);
  // console.log(filtered_data)
  // update the colors on the map
  svg.selectAll('path')
  .transition()
  .duration(100)
  .style('fill', d => {
  // find the corresponding data for this country
  const countrydata = filtered_data.find(
    country => Number(country.code) == Number(d.id) 
  )
  if (typeof(countrydata) == "undefined"){
    return colorScale(0)
  }
  else{
    return colorScale(countrydata.New_cases)
  }
  })
});



})

</script>
