# Proposal
## Research Topics
The final project targets to analyze and visualize the distribution of COVID-19 from different aspects, including how fatality varies around the globe, how the virus spreads out, when and how the variants transform and lead to long-lasting damage, and how recent daily/weekly cases fluctuate. 

Throughout these three years, COVID-19 has severely outbroken and struck the globe, paralyzed our economies and daily lives, and even transformed into different variants leading to continuing catastrophes. In this project, we are dedicated to taking advantage of different visualization tools and techniques from lectures to presenting how COVID-19 affects our globe in these years and digging into deeper insights into why the virus varies from time to time and from country to country.

## Data availability
### WHO Coronavirus (COVID-19) Dashboard
On the WHO Coronavirus (COVID-19) Dashboard [website](https://covid19.who.int/data), there are four datasets opened to be downloaded.

1. Daily cases and deaths by date reported to WHO
2. Latest reported counts of cases and deaths
3. Vaccination data
4. Vaccination metadata

#### Daily cases and deaths by date reported to WHO
[Daily cases and deaths by date reported to WHO](https://covid19.who.int/WHO-COVID-19-global-data.csv)

#### Latest reported counts of cases and deaths
[Latest reported counts of cases and deaths](https://covid19.who.int/WHO-COVID-19-global-table-data.csv)

#### Vaccination data
[Vaccination data](https://covid19.who.int/who-data/vaccination-data.csv)

#### Vaccination metadata
[Vaccination metadata](https://covid19.who.int/who-data/vaccination-metadata.csv)

**Published by:** 
The datasets above is published by the World Health Organization (WHO).

**Data format:** 
The format of the datasets is csv file.

**Frequency of updates: **

According to the description on the WHO COVID-19 Dashboard, the datasets is updated weekly. 

**Data size: **

#### Daily cases and deaths by date reported to WHO
File name: WHO-COVID-19-global-data.csv. Size: 10787 KB.

#### Latest reported counts of cases and deaths
File name: WHO-COVID-19-global-table-data.csv. Size: 17 KB.

#### Vaccination data
File name: vaccination-data.csv. Size: 49 KB.

#### Vaccination metadata
File name: vaccination-metadata.csv. Size: 88 KB.
